config/routes.rb
Waiting::Application.routes.draw do
  resources :backlog_items

  resources :backlogs

end

app/models/backlog.rb
class Backlog < ActiveRecord::Base
end

app/models/backlog_item.rb
class BacklogItem < ActiveRecord::Base
  belongs_to :backlog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/backlog_items_controller.rb
class BacklogItemsController < ApplicationController
  # GET /backlog_items
  # GET /backlog_items.xml
  def index
    @backlog_items = BacklogItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @backlog_items }
    end
  end

  # GET /backlog_items/1
  # GET /backlog_items/1.xml
  def show
    @backlog_item = BacklogItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @backlog_item }
    end
  end

  # GET /backlog_items/new
  # GET /backlog_items/new.xml
  def new
    @backlog_item = BacklogItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @backlog_item }
    end
  end

  # GET /backlog_items/1/edit
  def edit
    @backlog_item = BacklogItem.find(params[:id])
  end

  # POST /backlog_items
  # POST /backlog_items.xml
  def create
    @backlog_item = BacklogItem.new(params[:backlog_item])

    respond_to do |format|
      if @backlog_item.save
        format.html { redirect_to(@backlog_item, :notice => 'Backlog item was successfully created.') }
        format.xml  { render :xml => @backlog_item, :status => :created, :location => @backlog_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @backlog_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /backlog_items/1
  # PUT /backlog_items/1.xml
  def update
    @backlog_item = BacklogItem.find(params[:id])

    respond_to do |format|
      if @backlog_item.update_attributes(params[:backlog_item])
        format.html { redirect_to(@backlog_item, :notice => 'Backlog item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @backlog_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /backlog_items/1
  # DELETE /backlog_items/1.xml
  def destroy
    @backlog_item = BacklogItem.find(params[:id])
    @backlog_item.destroy

    respond_to do |format|
      format.html { redirect_to(backlog_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  # GET /backlogs
  # GET /backlogs.xml
  def index
    @backlogs = Backlog.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @backlogs }
    end
  end

  # GET /backlogs/1
  # GET /backlogs/1.xml
  def show
    @backlog = Backlog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @backlog }
    end
  end

  # GET /backlogs/new
  # GET /backlogs/new.xml
  def new
    @backlog = Backlog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @backlog }
    end
  end

  # GET /backlogs/1/edit
  def edit
    @backlog = Backlog.find(params[:id])
  end

  # POST /backlogs
  # POST /backlogs.xml
  def create
    @backlog = Backlog.new(params[:backlog])

    respond_to do |format|
      if @backlog.save
        format.html { redirect_to(@backlog, :notice => 'Backlog was successfully created.') }
        format.xml  { render :xml => @backlog, :status => :created, :location => @backlog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @backlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /backlogs/1
  # PUT /backlogs/1.xml
  def update
    @backlog = Backlog.find(params[:id])

    respond_to do |format|
      if @backlog.update_attributes(params[:backlog])
        format.html { redirect_to(@backlog, :notice => 'Backlog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @backlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /backlogs/1
  # DELETE /backlogs/1.xml
  def destroy
    @backlog = Backlog.find(params[:id])
    @backlog.destroy

    respond_to do |format|
      format.html { redirect_to(backlogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backlog_items_helper.rb
module BacklogItemsHelper
end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/views/backlog_items/_form.html.erb
<%= form_for(@backlog_item) do |f| %>
  <% if @backlog_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@backlog_item.errors.count, "error") %> prohibited this backlog_item from being saved:</h2>

      <ul>
      <% @backlog_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :backlog %><br />
    <%= f.text_field :backlog %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backlog_items/edit.html.erb
<h1>Editing backlog_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @backlog_item %> |
<%= link_to 'Back', backlog_items_path %>

app/views/backlog_items/index.html.erb
<h1>Listing backlog_items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Cost</th>
    <th>Priority</th>
    <th>Backlog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @backlog_items.each do |backlog_item| %>
  <tr>
    <td><%= backlog_item.name %></td>
    <td><%= backlog_item.description %></td>
    <td><%= backlog_item.cost %></td>
    <td><%= backlog_item.priority %></td>
    <td><%= backlog_item.backlog %></td>
    <td><%= link_to 'Show', backlog_item %></td>
    <td><%= link_to 'Edit', edit_backlog_item_path(backlog_item) %></td>
    <td><%= link_to 'Destroy', backlog_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Backlog item', new_backlog_item_path %>

app/views/backlog_items/new.html.erb
<h1>New backlog_item</h1>

<%= render 'form' %>

<%= link_to 'Back', backlog_items_path %>

app/views/backlog_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @backlog_item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @backlog_item.description %>
</p>

<p>
  <b>Cost:</b>
  <%= @backlog_item.cost %>
</p>

<p>
  <b>Priority:</b>
  <%= @backlog_item.priority %>
</p>

<p>
  <b>Backlog:</b>
  <%= @backlog_item.backlog %>
</p>


<%= link_to 'Edit', edit_backlog_item_path(@backlog_item) %> |
<%= link_to 'Back', backlog_items_path %>

app/views/backlogs/_form.html.erb
<%= form_for(@backlog) do |f| %>
  <% if @backlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@backlog.errors.count, "error") %> prohibited this backlog from being saved:</h2>

      <ul>
      <% @backlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backlogs/edit.html.erb
<h1>Editing backlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @backlog %> |
<%= link_to 'Back', backlogs_path %>

app/views/backlogs/index.html.erb
<h1>Listing backlogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @backlogs.each do |backlog| %>
  <tr>
    <td><%= backlog.name %></td>
    <td><%= backlog.description %></td>
    <td><%= link_to 'Show', backlog %></td>
    <td><%= link_to 'Edit', edit_backlog_path(backlog) %></td>
    <td><%= link_to 'Destroy', backlog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Backlog', new_backlog_path %>

app/views/backlogs/new.html.erb
<h1>New backlog</h1>

<%= render 'form' %>

<%= link_to 'Back', backlogs_path %>

app/views/backlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @backlog.name %>
</p>

<p>
  <b>Description:</b>
  <%= @backlog.description %>
</p>


<%= link_to 'Edit', edit_backlog_path(@backlog) %> |
<%= link_to 'Back', backlogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waiting</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>